"""Generate Luau ModuleScripts + model manifest from data.py.

Usage: python3 ark-blox/tools/gen.py
"""
import csv
import os
import re

import data as D

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "modules")

HEADER = "-- GENERATED by ark-blox/tools/gen.py from tools/data.py. Do not edit by hand.\n"


def lua(v, ind=0):
    pad = "\t" * ind
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, (list, tuple)):
        if not v:
            return "{}"
        if all(not isinstance(x, (dict, list, tuple)) for x in v):
            return "{ " + ", ".join(lua(x) for x in v) + " }"
        return "{\n" + "".join(f"{pad}\t{lua(x, ind + 1)},\n" for x in v) + pad + "}"
    if isinstance(v, dict):
        if not v:
            return "{}"
        parts = []
        for k, x in v.items():
            key = k if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k) else f"[{lua(k)}]"
            parts.append(f"{pad}\t{key} = {lua(x, ind + 1)},\n")
        return "{\n" + "".join(parts) + pad + "}"
    raise TypeError(v)


def pascal(name):
    return re.sub(r"[^A-Za-z0-9]", "", name.title().replace("-", " ")) if " " in name or "-" in name else name


manifest = []  # (assetPath, displayName, category, status, sketchfabQuery, note)


def add_model(path, name, cat, status, query="", note=""):
    manifest.append((path, name, cat, status, query, note))


# --------------------------------------------------------------- items
items = {}


def q(key, name):
    return D.MODEL_QUERIES.get(key, f"{name} realistic")


def add_item(iid, name, cat, sub, station=None, sources="Engram", model=None, status="todo", query=None, **extra):
    quality = cat in D.QUALITY_CATEGORIES and not (cat == "Tool" and iid in D.NO_QUALITY_TOOLS)
    entry = {
        "Id": iid,
        "DisplayName": name,
        "Category": cat,
        "SubCategory": sub,
        "CraftingStation": station,
        "Sources": sources.split(","),
        "QualityEnabled": quality,
        "Model": model,
    }
    entry.update(extra)
    items[iid] = entry
    add_model(model, name, cat, status, query if query is not None else q(iid, name), "")


for iid, name, sub in D.RESOURCES:
    st = "done" if iid in D.RESOURCE_MODELS_DONE else "todo"
    add_item(iid, name, "Resource", sub, None, "Harvest", f"ITEMS/Resources/{iid}", st,
             q(iid, name))

for iid, name, sub, station, src in D.TOOLS:
    add_item(iid, name, "Tool", sub, station, src, f"TOOLS/{iid}", query=q(iid, name))

for iid, name, sub, station, src, ammo in D.WEAPONS:
    add_item(iid, name, "Weapon", sub, station, src, f"WEAPONS/{iid}", query=q(iid, name), Ammo=ammo)

for iid, name, station in D.AMMO:
    add_item(iid, name, "Ammo", "Projectile", station, "Engram", f"AMMO/{iid}", query=q(iid, name))

for set_name, (pieces, station) in D.ARMOR_SETS.items():
    slots = D.SCUBA_SLOTS if set_name == "SCUBA" else D.ARMOR_SLOTS
    for piece, slot in zip(pieces, slots):
        iid = "Armor_" + re.sub(r"[^A-Za-z0-9]", "", piece)
        add_item(iid, piece, "Armor", set_name, station, D.LOOT if set_name != "Tek" else "Tekgram",
                 f"ARMOR/{set_name}/{re.sub(r'[^A-Za-z0-9]', '', piece)}",
                 query=D.SCUBA_QUERY[piece] if set_name == "SCUBA" else
                 f"{D.ARMOR_QUERY_SET[set_name]} {D.ARMOR_QUERY_SLOT[slot]}|{D.ARMOR_QUERY_SLOT[slot]} realistic", Slot=slot, ArmorSet=set_name)

for iid, name, station in D.SHIELDS:
    add_item(iid, name, "Shield", "Shield", station, D.LOOT if iid != "TekShield" else "Tekgram",
             f"SHIELDS/{iid}", query=q(iid, name))

for creature, stype in D.SADDLES:
    suffix = {"Platform": "PlatformSaddle", "Tek": "TekSaddle"}.get(stype, "Saddle")
    iid = f"{creature}{suffix}"
    label = {"Platform": "Platform Saddle", "Tek": "Tek Saddle"}.get(stype, "Saddle")
    st = "done" if (creature, stype) in D.SADDLE_MODELS_DONE else "todo"
    add_item(iid, f"{creature} {label}", "Saddle", stype, D.SADDLE_STATION[stype],
             D.LOOT if stype != "Tek" else "Tekgram", f"SADDLES/{iid}", st,
             D.SADDLE_QUERY[stype].format(c=creature),
             Creature=creature)

# --------------------------------------------------------------- structures
def pipe_query(sid, name):
    if "IrrigationPipe" not in sid:
        return None
    mat, kind = sid.split("IrrigationPipe")
    return f"{mat.lower()} {D.PIPE_QUERIES[kind]}|{D.PIPE_QUERIES[kind]}"


structures = {}
for sid, name, cat, fn, slots, fuel, status in D.STRUCTURES:
    folder = {"Crafting": "CRAFTING", "Storage": "STORAGE", "Farming": "FARMING", "Electrical": "ELECTRICAL",
              "Defense": "DEFENSE", "Bed": "BEDS", "Decor": "DECOR", "Utility": "CRAFTING"}[cat]
    structures[sid] = {
        "Id": sid, "DisplayName": name, "Category": cat, "Function": fn,
        "Slots": slots, "Fuel": fuel.split(",") if fuel else None,
        "QualityEnabled": False, "Model": f"{folder}/{sid}",
    }
    add_model(f"{folder}/{sid}", name, "Structure:" + cat, status, pipe_query(sid, name) or q(sid, name),
              "made in previous session" if status == "done" else "")

for sid, name in D.TEK_FUNCTIONAL:
    structures[sid] = {"Id": sid, "DisplayName": name, "Category": "Tek", "Function": "Tek utility",
                       "Slots": None, "Fuel": ["Element"], "QualityEnabled": False, "Model": f"TEK/{sid}"}
    add_model(f"TEK/{sid}", name, "Structure:Tek", "todo", q(sid, name))

building = {}
for tier, pieces in D.BUILDING_PIECES.items():
    for piece in pieces:
        effective = tier
        if tier == "Stone" and piece in D.STONE_TIER_WOOD_LOOK:
            effective = "Stone"
        pid = f"{tier}_{re.sub(r'[^A-Za-z0-9]', '', piece)}"
        building[pid] = {"Id": pid, "DisplayName": f"{tier} {piece}", "Tier": effective, "Piece": piece,
                         "QualityEnabled": False, "Model": f"BUILDINGS/{tier}/{re.sub(r'[^A-Za-z0-9]', '', piece)}"}
        add_model(f"BUILDINGS/{tier}/{re.sub(r'[^A-Za-z0-9]', '', piece)}", f"{tier} {piece}",
                  "Building:" + tier, "keep", "", "owner: existing building models are good enough")

# --------------------------------------------------------------- harvest nodes
nodes = {}
for nid, name, where, tool, drops in D.HARVEST_NODES:
    nodes[nid] = {"Id": nid, "DisplayName": name, "Biomes": where.split(","), "Tool": tool,
                  "Drops": [{"Item": i, "Weight": w} for i, w in drops], "Model": f"NODES/{nid}"}
    add_model(f"NODES/{nid}", name, "HarvestNode", "done", "", "made in previous session")
corpses = {}
for cid, creature, tool, drops in D.CORPSE_SOURCES:
    corpses[cid] = {"Id": cid, "Creature": creature, "Tool": tool,
                    "Drops": [{"Item": i, "Weight": w} for i, w in drops]}

# --------------------------------------------------------------- validate
known = set(items) | {"Gasoline", "Sparkpowder", "Element"}
for n in list(nodes.values()) + list(corpses.values()):
    for d in n["Drops"]:
        assert d["Item"] in items, f"{n['Id']}: unknown drop {d['Item']}"
for it in items.values():
    for a in it.get("Ammo", []):
        assert a in items, f"{it['Id']}: unknown ammo {a}"
    st = it["CraftingStation"]
    assert st in (None, "Inventory") or st in structures, f"{it['Id']}: unknown station {st}"
ids = [m[0] for m in manifest]
assert len(ids) == len(set(ids)), "duplicate model path"

# --------------------------------------------------------------- write
os.makedirs(OUT, exist_ok=True)


def write(name, doc, body):
    with open(os.path.join(OUT, name + ".lua"), "w") as f:
        f.write(HEADER + f"-- {doc}\n\n" + body)


tiers = {t[0]: {"Id": t[0], "Name": t[1], "Index": i + 1, "Multiplier": t[2], "Color": t[3]}
         for i, t in enumerate(D.QUALITY_TIERS)}
qcats = {c: True for c in sorted(D.QUALITY_CATEGORIES)}

write("QualityTiers", "ASE vanilla item quality tiers (no Transcendent).", f"""local QualityTiers = {{}}

QualityTiers.Order = {lua([t[0] for t in D.QUALITY_TIERS])}

QualityTiers.Tiers = {lua(tiers)}

-- Categories whose items roll quality. Structures never do.
QualityTiers.Categories = {lua(qcats)}

-- Building progression is separate from item quality. Greenhouse is a special set.
QualityTiers.BuildingTiers = {lua(D.BUILDING_TIERS)}

function QualityTiers.Get(id)
	return QualityTiers.Tiers[id] or QualityTiers.Tiers.PRIMITIVE
end

-- Returns the highest tier whose multiplier threshold is <= rolled multiplier.
function QualityTiers.FromMultiplier(mult)
	local best = QualityTiers.Tiers.PRIMITIVE
	for _, id in ipairs(QualityTiers.Order) do
		local t = QualityTiers.Tiers[id]
		if mult >= t.Multiplier then
			best = t
		end
	end
	return best
end

-- Scale a base stat (damage, durability, armor) by quality.
function QualityTiers.ScaleStat(base, id)
	return base * QualityTiers.Get(id).Multiplier
end

return QualityTiers
""")

write("HarvestNodeDatabase", "The Island resource nodes and corpse sources (Weight = relative yield share).",
      f"""local HarvestNodeDatabase = {{}}

HarvestNodeDatabase.Nodes = {lua(nodes)}

-- Corpse sources use the creature's own model from CreatureLibrary.
-- Creature "*Tag" rows are generic fallbacks by body type.
HarvestNodeDatabase.Corpses = {lua(corpses)}

function HarvestNodeDatabase.RollDrop(nodeId, rng)
	local node = HarvestNodeDatabase.Nodes[nodeId] or HarvestNodeDatabase.Corpses[nodeId]
	if not node then
		return nil
	end
	rng = rng or Random.new()
	local total = 0
	for _, d in ipairs(node.Drops) do
		total += d.Weight
	end
	local pick = rng:NextNumber() * total
	for _, d in ipairs(node.Drops) do
		pick -= d.Weight
		if pick <= 0 then
			return d.Item
		end
	end
	return node.Drops[#node.Drops].Item
end

return HarvestNodeDatabase
""")

write("StructureDatabase", "Placeable structures (crafting, storage, farming, electrical, defense, beds) and building pieces.",
      f"""local StructureDatabase = {{}}

-- Slots/Fuel follow the ASE wiki; Slots = nil means not a container.
StructureDatabase.Structures = {lua(structures)}

-- Building pieces per tier. Models already exist (keep); these are data only.
-- Reinforced doors/gates/windows are Stone tier even though they look wooden.
StructureDatabase.BuildingPieces = {lua(building)}

function StructureDatabase.Get(id)
	return StructureDatabase.Structures[id] or StructureDatabase.BuildingPieces[id]
end

function StructureDatabase.ByCategory(category)
	local out = {{}}
	for _, s in pairs(StructureDatabase.Structures) do
		if s.Category == category then
			table.insert(out, s)
		end
	end
	return out
end

return StructureDatabase
""")

write("ItemDatabase_Island", "Inventory items: resources, tools, weapons, ammo, armor, shields, saddles.",
      f"""local QualityTiers = require(script.Parent.QualityTiers)

local ItemDatabase = {{}}

-- One entry per item. Quality is an instance property, never a separate model:
-- {{ Id = "MetalPick", Quality = "MASTERCRAFT", Multiplier = 7.3 }}
ItemDatabase.Items = {lua(items)}

function ItemDatabase.Get(id)
	return ItemDatabase.Items[id]
end

-- Build an item instance. Items without QualityEnabled always get PRIMITIVE.
function ItemDatabase.NewInstance(id, qualityId, multiplier)
	local def = ItemDatabase.Items[id]
	assert(def, "unknown item " .. tostring(id))
	local tier = def.QualityEnabled and QualityTiers.Get(qualityId) or QualityTiers.Tiers.PRIMITIVE
	return {{
		Id = id,
		Quality = tier.Id,
		Multiplier = def.QualityEnabled and (multiplier or tier.Multiplier) or 1,
	}}
end

function ItemDatabase.ByCategory(category)
	local out = {{}}
	for _, it in pairs(ItemDatabase.Items) do
		if it.Category == category then
			table.insert(out, it)
		end
	end
	return out
end

return ItemDatabase
""")

manifest.sort(key=lambda m: m[0])
with open(os.path.join(ROOT, "model_manifest.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["AssetPath", "DisplayName", "Category", "Status", "SketchfabQuery", "Note"])
    w.writerows(manifest)

from collections import Counter
c = Counter(m[3] for m in manifest)
todo = Counter(m[2].split(":")[-1] if m[3] == "todo" else None for m in manifest)
todo.pop(None, None)
print("items", len(items), "structures", len(structures), "building", len(building), "nodes", len(nodes),
      "corpses", len(corpses))
print("model status", dict(c))
print("todo by category", dict(sorted(todo.items())))
