"""Download the chosen Sketchfab models (Chosen=1 in model_candidates.csv) as .glb.

Usage:
  export SKETCHFAB_TOKEN=...   # https://sketchfab.com/settings/password -> API token
  python3 ark-blox/tools/sketchfab_download.py [--only PREFIX] [--out DIR]

Files land in DIR/<AssetPath>.glb (default ark-blox/models_src/, git-ignored) so the
folder tree matches the Studio asset folders. Import them with Studio's 3D Importer
(File > Import 3D), then run the model through Blender's Decimate modifier first when
NeedsDecimate=1 (Roblox allows 20k triangles per MeshPart).
CREDITS.md is rewritten with every chosen CC-BY author, which the license requires.
"""
import argparse
import csv
import json
import os
import sys
import time
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CANDIDATES = os.path.join(ROOT, "model_candidates.csv")


def api(url, token):
    req = urllib.request.Request(url, headers={"Authorization": f"Token {token}", "User-Agent": "ark-blox"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def fetch(url, dest):
    tmp = dest + ".part"
    with urllib.request.urlopen(url, timeout=300) as r, open(tmp, "wb") as f:
        while chunk := r.read(1 << 20):
            f.write(chunk)
    os.replace(tmp, dest)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="")
    ap.add_argument("--out", default=os.path.join(ROOT, "models_src"))
    a = ap.parse_args()

    rows = [r for r in csv.DictReader(open(CANDIDATES)) if r["Chosen"] == "1"]
    # CREDITS.md covers every chosen model, downloaded or not, so it stays in sync with the CSV.
    with open(os.path.join(ROOT, "CREDITS.md"), "w") as f:
        f.write("# Model credits\n\nModels from Sketchfab, used under the license listed. "
                "Generated by `tools/sketchfab_download.py` from `model_candidates.csv`.\n\n"
                "| Asset | Model | Author | License |\n|---|---|---|---|\n")
        for r in rows:
            f.write(f"| `{r['AssetPath']}` | [{r['Name']}]({r['Url']}) | "
                    f"[{r['Author']}](https://sketchfab.com/{r['Author']}) | {r['License']} |\n")

    token = os.environ.get("SKETCHFAB_TOKEN")
    if not token:
        sys.exit("CREDITS.md updated. Set SKETCHFAB_TOKEN to download the models.")
    for r in rows:
        if not r["AssetPath"].startswith(a.only):
            continue
        dest = os.path.join(a.out, r["AssetPath"] + ".glb")
        if os.path.exists(dest) or os.path.exists(dest[:-4] + ".gltf.zip"):
            continue
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        try:
            links = api(f"https://api.sketchfab.com/v3/models/{r['Uid']}/download", token)
            if "glb" not in links:  # older uploads only ship a zipped glTF
                dest = dest[:-4] + ".gltf.zip"
            fetch(links.get("glb", links.get("gltf"))["url"], dest)
            print("ok  ", r["AssetPath"], f"({r['Faces']} faces{', decimate' if r['NeedsDecimate'] == '1' else ''})")
        except Exception as e:
            print("FAIL", r["AssetPath"], e)
        time.sleep(1)


if __name__ == "__main__":
    main()
