-- GENERATED by ark-blox/tools/gen.py from tools/data.py. Do not edit by hand.
-- The Island resource nodes and corpse sources (Weight = relative yield share).

local HarvestNodeDatabase = {}

HarvestNodeDatabase.Nodes = {
	SMALL_ROCK = {
		Id = "SMALL_ROCK",
		DisplayName = "Small Rock",
		Biomes = { "All" },
		Tool = "Any",
		Drops = {
			{
				Item = "Stone",
				Weight = 70,
			},
			{
				Item = "Flint",
				Weight = 30,
			},
		},
		Model = "NODES/SMALL_ROCK",
	},
	STONE_ROCK = {
		Id = "STONE_ROCK",
		DisplayName = "Stone Rock",
		Biomes = { "All" },
		Tool = "Any",
		Drops = {
			{
				Item = "Stone",
				Weight = 70,
			},
			{
				Item = "Flint",
				Weight = 30,
			},
		},
		Model = "NODES/STONE_ROCK",
	},
	LARGE_STONE_ROCK = {
		Id = "LARGE_STONE_ROCK",
		DisplayName = "Large Stone Rock",
		Biomes = { "All" },
		Tool = "Any",
		Drops = {
			{
				Item = "Stone",
				Weight = 70,
			},
			{
				Item = "Flint",
				Weight = 30,
			},
		},
		Model = "NODES/LARGE_STONE_ROCK",
	},
	RIVER_ROCK = {
		Id = "RIVER_ROCK",
		DisplayName = "River Rock",
		Biomes = { "River" },
		Tool = "Any",
		Drops = {
			{
				Item = "Stone",
				Weight = 60,
			},
			{
				Item = "Flint",
				Weight = 35,
			},
			{
				Item = "Metal",
				Weight = 5,
			},
		},
		Model = "NODES/RIVER_ROCK",
	},
	METAL_ROCK = {
		Id = "METAL_ROCK",
		DisplayName = "Metal Rock",
		Biomes = { "Mountain", "Snow", "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Metal",
				Weight = 45,
			},
			{
				Item = "Stone",
				Weight = 35,
			},
			{
				Item = "Flint",
				Weight = 20,
			},
		},
		Model = "NODES/METAL_ROCK",
	},
	RICH_METAL_ROCK = {
		Id = "RICH_METAL_ROCK",
		DisplayName = "Rich Metal Rock",
		Biomes = { "Mountain", "Volcano", "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Metal",
				Weight = 65,
			},
			{
				Item = "Stone",
				Weight = 25,
			},
			{
				Item = "Flint",
				Weight = 10,
			},
		},
		Model = "NODES/RICH_METAL_ROCK",
	},
	OBSIDIAN_ROCK = {
		Id = "OBSIDIAN_ROCK",
		DisplayName = "Obsidian Rock",
		Biomes = { "Volcano", "Mountain", "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Obsidian",
				Weight = 75,
			},
			{
				Item = "Stone",
				Weight = 25,
			},
		},
		Model = "NODES/OBSIDIAN_ROCK",
	},
	CRYSTAL_NODE = {
		Id = "CRYSTAL_NODE",
		DisplayName = "Crystal Node",
		Biomes = { "Mountain", "Snow", "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Crystal",
				Weight = 80,
			},
			{
				Item = "Stone",
				Weight = 18,
			},
			{
				Item = "RareMushroom",
				Weight = 2,
			},
		},
		Model = "NODES/CRYSTAL_NODE",
	},
	OIL_ROCK = {
		Id = "OIL_ROCK",
		DisplayName = "Oil Rock",
		Biomes = { "Snow", "Beach", "Volcano" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Oil",
				Weight = 70,
			},
			{
				Item = "Stone",
				Weight = 30,
			},
		},
		Model = "NODES/OIL_ROCK",
	},
	OIL_ROCK_SNOW = {
		Id = "OIL_ROCK_SNOW",
		DisplayName = "Oil Rock (Snow Coast)",
		Biomes = { "Snow" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Oil",
				Weight = 70,
			},
			{
				Item = "Stone",
				Weight = 30,
			},
		},
		Model = "NODES/OIL_ROCK_SNOW",
	},
	UNDERWATER_OIL_NODE = {
		Id = "UNDERWATER_OIL_NODE",
		DisplayName = "Underwater Oil Node",
		Biomes = { "Ocean", "UnderwaterCave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Oil",
				Weight = 90,
			},
			{
				Item = "Stone",
				Weight = 10,
			},
		},
		Model = "NODES/UNDERWATER_OIL_NODE",
	},
	CAVE_ROCK = {
		Id = "CAVE_ROCK",
		DisplayName = "Cave Rock",
		Biomes = { "Cave" },
		Tool = "Any",
		Drops = {
			{
				Item = "Stone",
				Weight = 65,
			},
			{
				Item = "Flint",
				Weight = 35,
			},
		},
		Model = "NODES/CAVE_ROCK",
	},
	CAVE_METAL_NODE = {
		Id = "CAVE_METAL_NODE",
		DisplayName = "Cave Metal Node",
		Biomes = { "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Metal",
				Weight = 60,
			},
			{
				Item = "Stone",
				Weight = 40,
			},
		},
		Model = "NODES/CAVE_METAL_NODE",
	},
	CAVE_CRYSTAL = {
		Id = "CAVE_CRYSTAL",
		DisplayName = "Cave Crystal",
		Biomes = { "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Crystal",
				Weight = 100,
			},
		},
		Model = "NODES/CAVE_CRYSTAL",
	},
	CAVE_OBSIDIAN = {
		Id = "CAVE_OBSIDIAN",
		DisplayName = "Cave Obsidian",
		Biomes = { "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Obsidian",
				Weight = 100,
			},
		},
		Model = "NODES/CAVE_OBSIDIAN",
	},
	CAVE_OIL_NODE = {
		Id = "CAVE_OIL_NODE",
		DisplayName = "Cave Oil Node",
		Biomes = { "Cave" },
		Tool = "Pick",
		Drops = {
			{
				Item = "Oil",
				Weight = 100,
			},
		},
		Model = "NODES/CAVE_OIL_NODE",
	},
	TREE_SMALL = {
		Id = "TREE_SMALL",
		DisplayName = "Small Tree",
		Biomes = { "Grassland", "Jungle", "Beach" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 60,
			},
			{
				Item = "Thatch",
				Weight = 40,
			},
		},
		Model = "NODES/TREE_SMALL",
	},
	TREE_MEDIUM = {
		Id = "TREE_MEDIUM",
		DisplayName = "Medium Tree",
		Biomes = { "Grassland", "Jungle" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 60,
			},
			{
				Item = "Thatch",
				Weight = 40,
			},
		},
		Model = "NODES/TREE_MEDIUM",
	},
	TREE_LARGE = {
		Id = "TREE_LARGE",
		DisplayName = "Large Tree",
		Biomes = { "Jungle", "Grassland" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 65,
			},
			{
				Item = "Thatch",
				Weight = 35,
			},
		},
		Model = "NODES/TREE_LARGE",
	},
	JUNGLE_TREE = {
		Id = "JUNGLE_TREE",
		DisplayName = "Jungle Tree",
		Biomes = { "Jungle" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 60,
			},
			{
				Item = "Thatch",
				Weight = 40,
			},
		},
		Model = "NODES/JUNGLE_TREE",
	},
	REDWOOD_TREE = {
		Id = "REDWOOD_TREE",
		DisplayName = "Redwood Tree",
		Biomes = { "Redwoods" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 70,
			},
			{
				Item = "Thatch",
				Weight = 30,
			},
		},
		Model = "NODES/REDWOOD_TREE",
	},
	DEAD_TREE = {
		Id = "DEAD_TREE",
		DisplayName = "Dead Tree",
		Biomes = { "Snow", "Volcano" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 90,
			},
			{
				Item = "Thatch",
				Weight = 10,
			},
		},
		Model = "NODES/DEAD_TREE",
	},
	TREE_STUMP = {
		Id = "TREE_STUMP",
		DisplayName = "Tree Stump",
		Biomes = { "All" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 60,
			},
			{
				Item = "Thatch",
				Weight = 40,
			},
		},
		Model = "NODES/TREE_STUMP",
	},
	SWAMP_TREE = {
		Id = "SWAMP_TREE",
		DisplayName = "Swamp Tree",
		Biomes = { "Swamp" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 60,
			},
			{
				Item = "Thatch",
				Weight = 40,
			},
		},
		Model = "NODES/SWAMP_TREE",
	},
	SWAMP_ROOT_TREE = {
		Id = "SWAMP_ROOT_TREE",
		DisplayName = "Swamp Root Tree",
		Biomes = { "Swamp" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 55,
			},
			{
				Item = "Thatch",
				Weight = 35,
			},
			{
				Item = "RareMushroom",
				Weight = 10,
			},
		},
		Model = "NODES/SWAMP_ROOT_TREE",
	},
	SAP_TREE = {
		Id = "SAP_TREE",
		DisplayName = "Redwood Tree (Sap Tap spot)",
		Biomes = { "Redwoods" },
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Wood",
				Weight = 70,
			},
			{
				Item = "Thatch",
				Weight = 30,
			},
		},
		Model = "NODES/SAP_TREE",
	},
	BUSH = {
		Id = "BUSH",
		DisplayName = "Bush",
		Biomes = { "All" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 40,
			},
			{
				Item = "Amarberry",
				Weight = 10,
			},
			{
				Item = "Azulberry",
				Weight = 10,
			},
			{
				Item = "Mejoberry",
				Weight = 8,
			},
			{
				Item = "Narcoberry",
				Weight = 8,
			},
			{
				Item = "Stimberry",
				Weight = 8,
			},
			{
				Item = "Tintoberry",
				Weight = 10,
			},
			{
				Item = "AmarberrySeed",
				Weight = 1,
			},
			{
				Item = "CitronalSeed",
				Weight = 1,
			},
			{
				Item = "LongrassSeed",
				Weight = 1,
			},
			{
				Item = "RockarrotSeed",
				Weight = 1,
			},
			{
				Item = "SavorootSeed",
				Weight = 1,
			},
		},
		Model = "NODES/BUSH",
	},
	BERRY_BUSH = {
		Id = "BERRY_BUSH",
		DisplayName = "Berry Bush",
		Biomes = { "All" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 30,
			},
			{
				Item = "Amarberry",
				Weight = 12,
			},
			{
				Item = "Azulberry",
				Weight = 12,
			},
			{
				Item = "Mejoberry",
				Weight = 12,
			},
			{
				Item = "Narcoberry",
				Weight = 10,
			},
			{
				Item = "Stimberry",
				Weight = 10,
			},
			{
				Item = "Tintoberry",
				Weight = 12,
			},
			{
				Item = "MejoberrySeed",
				Weight = 1,
			},
			{
				Item = "NarcoberrySeed",
				Weight = 1,
			},
		},
		Model = "NODES/BERRY_BUSH",
	},
	SNOW_BUSH = {
		Id = "SNOW_BUSH",
		DisplayName = "Snow Bush",
		Biomes = { "Snow" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 45,
			},
			{
				Item = "Amarberry",
				Weight = 10,
			},
			{
				Item = "Mejoberry",
				Weight = 10,
			},
			{
				Item = "Narcoberry",
				Weight = 10,
			},
			{
				Item = "Stimberry",
				Weight = 10,
			},
			{
				Item = "Tintoberry",
				Weight = 10,
			},
			{
				Item = "RareFlower",
				Weight = 5,
			},
		},
		Model = "NODES/SNOW_BUSH",
	},
	RED_MOUNTAIN_BUSH = {
		Id = "RED_MOUNTAIN_BUSH",
		DisplayName = "Red Mountain Bush",
		Biomes = { "Mountain" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 40,
			},
			{
				Item = "Azulberry",
				Weight = 10,
			},
			{
				Item = "Mejoberry",
				Weight = 10,
			},
			{
				Item = "Narcoberry",
				Weight = 10,
			},
			{
				Item = "Tintoberry",
				Weight = 10,
			},
			{
				Item = "RareFlower",
				Weight = 15,
			},
			{
				Item = "PlantSpeciesXSeed",
				Weight = 5,
			},
		},
		Model = "NODES/RED_MOUNTAIN_BUSH",
	},
	REDWOOD_BUSH = {
		Id = "REDWOOD_BUSH",
		DisplayName = "Redwood Bush",
		Biomes = { "Redwoods" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 45,
			},
			{
				Item = "Amarberry",
				Weight = 10,
			},
			{
				Item = "Azulberry",
				Weight = 10,
			},
			{
				Item = "Mejoberry",
				Weight = 10,
			},
			{
				Item = "Stimberry",
				Weight = 10,
			},
			{
				Item = "Tintoberry",
				Weight = 15,
			},
		},
		Model = "NODES/REDWOOD_BUSH",
	},
	SWAMP_BUSH = {
		Id = "SWAMP_BUSH",
		DisplayName = "Swamp Bush",
		Biomes = { "Swamp" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 50,
			},
			{
				Item = "Azulberry",
				Weight = 12,
			},
			{
				Item = "Mejoberry",
				Weight = 12,
			},
			{
				Item = "Narcoberry",
				Weight = 13,
			},
			{
				Item = "Stimberry",
				Weight = 13,
			},
		},
		Model = "NODES/SWAMP_BUSH",
	},
	SWAMP_CATTAIL = {
		Id = "SWAMP_CATTAIL",
		DisplayName = "Swamp Cattail",
		Biomes = { "Swamp" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 40,
			},
			{
				Item = "Amarberry",
				Weight = 10,
			},
			{
				Item = "Narcoberry",
				Weight = 10,
			},
			{
				Item = "Stimberry",
				Weight = 10,
			},
			{
				Item = "RareFlower",
				Weight = 25,
			},
			{
				Item = "PlantSpeciesXSeed",
				Weight = 5,
			},
		},
		Model = "NODES/SWAMP_CATTAIL",
	},
	SWAMP_BRAMBLE = {
		Id = "SWAMP_BRAMBLE",
		DisplayName = "Swamp Bramble",
		Biomes = { "Swamp" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 40,
			},
			{
				Item = "Azulberry",
				Weight = 10,
			},
			{
				Item = "Mejoberry",
				Weight = 10,
			},
			{
				Item = "Tintoberry",
				Weight = 10,
			},
			{
				Item = "RareFlower",
				Weight = 25,
			},
			{
				Item = "PlantSpeciesXSeed",
				Weight = 5,
			},
		},
		Model = "NODES/SWAMP_BRAMBLE",
	},
	RARE_MUSHROOM_SOURCE = {
		Id = "RARE_MUSHROOM_SOURCE",
		DisplayName = "Rare Mushroom Source",
		Biomes = { "Swamp", "Cave" },
		Tool = "Hand",
		Drops = {
			{
				Item = "RareMushroom",
				Weight = 100,
			},
		},
		Model = "NODES/RARE_MUSHROOM_SOURCE",
	},
	SAP_TAP = {
		Id = "SAP_TAP",
		DisplayName = "Tree Sap Tap",
		Biomes = { "Redwoods" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Sap",
				Weight = 100,
			},
		},
		Model = "NODES/SAP_TAP",
	},
	GIANT_BEE_HIVE = {
		Id = "GIANT_BEE_HIVE",
		DisplayName = "Giant Bee Hive",
		Biomes = { "Redwoods" },
		Tool = "Hand",
		Drops = {
			{
				Item = "GiantBeeHoney",
				Weight = 100,
			},
		},
		Model = "NODES/GIANT_BEE_HIVE",
	},
	BEAVER_DAM = {
		Id = "BEAVER_DAM",
		DisplayName = "Giant Beaver Dam",
		Biomes = { "River", "Swamp", "Redwoods" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Wood",
				Weight = 40,
			},
			{
				Item = "CementingPaste",
				Weight = 25,
			},
			{
				Item = "RareFlower",
				Weight = 12,
			},
			{
				Item = "RareMushroom",
				Weight = 12,
			},
			{
				Item = "SilicaPearls",
				Weight = 11,
			},
		},
		Model = "NODES/BEAVER_DAM",
	},
	PEARL_CLAM = {
		Id = "PEARL_CLAM",
		DisplayName = "Pearl Clam",
		Biomes = { "Ocean", "Snow" },
		Tool = "Hand",
		Drops = {
			{
				Item = "SilicaPearls",
				Weight = 100,
			},
		},
		Model = "NODES/PEARL_CLAM",
	},
	UNDERWATER_PEARL_NODE = {
		Id = "UNDERWATER_PEARL_NODE",
		DisplayName = "Underwater Pearl Node",
		Biomes = { "UnderwaterCave" },
		Tool = "Hand",
		Drops = {
			{
				Item = "SilicaPearls",
				Weight = 100,
			},
		},
		Model = "NODES/UNDERWATER_PEARL_NODE",
	},
	UNDERWATER_CAVE_PEARL_CLAM = {
		Id = "UNDERWATER_CAVE_PEARL_CLAM",
		DisplayName = "Underwater Cave Pearl Clam",
		Biomes = { "UnderwaterCave" },
		Tool = "Hand",
		Drops = {
			{
				Item = "SilicaPearls",
				Weight = 100,
			},
		},
		Model = "NODES/UNDERWATER_CAVE_PEARL_CLAM",
	},
	SWAMP_CAVE_VEGETATION = {
		Id = "SWAMP_CAVE_VEGETATION",
		DisplayName = "Swamp Cave Vegetation",
		Biomes = { "Cave" },
		Tool = "Hand",
		Drops = {
			{
				Item = "Fiber",
				Weight = 50,
			},
			{
				Item = "Azulberry",
				Weight = 15,
			},
			{
				Item = "Mejoberry",
				Weight = 15,
			},
			{
				Item = "RareMushroom",
				Weight = 20,
			},
		},
		Model = "NODES/SWAMP_CAVE_VEGETATION",
	},
}

-- Corpse sources use the creature's own model from CreatureLibrary.
-- Creature "*Tag" rows are generic fallbacks by body type.
HarvestNodeDatabase.Corpses = {
	TRILOBITE_CORPSE = {
		Id = "TRILOBITE_CORPSE",
		Creature = "Trilobite",
		Tool = "Pick",
		Drops = {
			{
				Item = "Chitin",
				Weight = 40,
			},
			{
				Item = "RawMeat",
				Weight = 15,
			},
			{
				Item = "Oil",
				Weight = 20,
			},
			{
				Item = "SilicaPearls",
				Weight = 20,
			},
			{
				Item = "BlackPearl",
				Weight = 5,
			},
		},
	},
	EURYPTERID_CORPSE = {
		Id = "EURYPTERID_CORPSE",
		Creature = "Eurypterid",
		Tool = "Pick",
		Drops = {
			{
				Item = "Chitin",
				Weight = 45,
			},
			{
				Item = "Oil",
				Weight = 25,
			},
			{
				Item = "SilicaPearls",
				Weight = 25,
			},
			{
				Item = "BlackPearl",
				Weight = 5,
			},
		},
	},
	LEECH_CORPSE = {
		Id = "LEECH_CORPSE",
		Creature = "Leech",
		Tool = "Any",
		Drops = {
			{
				Item = "LeechBlood",
				Weight = 40,
			},
			{
				Item = "Chitin",
				Weight = 30,
			},
			{
				Item = "SilicaPearls",
				Weight = 30,
			},
		},
	},
	AMMONITE_CORPSE = {
		Id = "AMMONITE_CORPSE",
		Creature = "Ammonite",
		Tool = "Any",
		Drops = {
			{
				Item = "Chitin",
				Weight = 35,
			},
			{
				Item = "AmmoniteBile",
				Weight = 25,
			},
			{
				Item = "BlackPearl",
				Weight = 10,
			},
			{
				Item = "SilicaPearls",
				Weight = 15,
			},
			{
				Item = "RawMeat",
				Weight = 15,
			},
		},
	},
	TUSOTEUTHIS_CORPSE = {
		Id = "TUSOTEUTHIS_CORPSE",
		Creature = "Tusoteuthis",
		Tool = "Any",
		Drops = {
			{
				Item = "BlackPearl",
				Weight = 15,
			},
			{
				Item = "Oil",
				Weight = 25,
			},
			{
				Item = "RawFishMeat",
				Weight = 25,
			},
			{
				Item = "RawPrimeFishMeat",
				Weight = 15,
			},
			{
				Item = "TusoteuthisTentacle",
				Weight = 20,
			},
		},
	},
	KAIRUKU_CORPSE = {
		Id = "KAIRUKU_CORPSE",
		Creature = "Kairuku",
		Tool = "Pick",
		Drops = {
			{
				Item = "OrganicPolymer",
				Weight = 50,
			},
			{
				Item = "Hide",
				Weight = 25,
			},
			{
				Item = "RawMeat",
				Weight = 25,
			},
		},
	},
	ANGLERFISH_CORPSE = {
		Id = "ANGLERFISH_CORPSE",
		Creature = "Angler",
		Tool = "Any",
		Drops = {
			{
				Item = "AnglerGel",
				Weight = 40,
			},
			{
				Item = "RawFishMeat",
				Weight = 40,
			},
			{
				Item = "RawPrimeFishMeat",
				Weight = 20,
			},
		},
	},
	ACHATINA = {
		Id = "ACHATINA",
		Creature = "Achatina",
		Tool = "Hand",
		Drops = {
			{
				Item = "AchatinaPaste",
				Weight = 100,
			},
		},
	},
	DINO_CORPSE = {
		Id = "DINO_CORPSE",
		Creature = "*",
		Tool = "Hatchet",
		Drops = {
			{
				Item = "RawMeat",
				Weight = 60,
			},
			{
				Item = "Hide",
				Weight = 40,
			},
		},
	},
	LARGE_DINO_CORPSE = {
		Id = "LARGE_DINO_CORPSE",
		Creature = "*Large",
		Tool = "Hatchet",
		Drops = {
			{
				Item = "RawMeat",
				Weight = 50,
			},
			{
				Item = "RawPrimeMeat",
				Weight = 10,
			},
			{
				Item = "Hide",
				Weight = 40,
			},
		},
	},
	HORNED_CORPSE = {
		Id = "HORNED_CORPSE",
		Creature = "*Horned",
		Tool = "Pick",
		Drops = {
			{
				Item = "Keratin",
				Weight = 40,
			},
			{
				Item = "Hide",
				Weight = 30,
			},
			{
				Item = "RawMeat",
				Weight = 30,
			},
		},
	},
	FURRY_CORPSE = {
		Id = "FURRY_CORPSE",
		Creature = "*Furry",
		Tool = "Hatchet",
		Drops = {
			{
				Item = "Pelt",
				Weight = 35,
			},
			{
				Item = "Hide",
				Weight = 30,
			},
			{
				Item = "RawMeat",
				Weight = 35,
			},
		},
	},
	INSECT_CORPSE = {
		Id = "INSECT_CORPSE",
		Creature = "*Insect",
		Tool = "Pick",
		Drops = {
			{
				Item = "Chitin",
				Weight = 70,
			},
			{
				Item = "RawMeat",
				Weight = 30,
			},
		},
	},
	FISH_CORPSE = {
		Id = "FISH_CORPSE",
		Creature = "*Fish",
		Tool = "Any",
		Drops = {
			{
				Item = "RawFishMeat",
				Weight = 100,
			},
		},
	},
	LARGE_FISH_CORPSE = {
		Id = "LARGE_FISH_CORPSE",
		Creature = "*LargeFish",
		Tool = "Any",
		Drops = {
			{
				Item = "RawFishMeat",
				Weight = 80,
			},
			{
				Item = "RawPrimeFishMeat",
				Weight = 20,
			},
		},
	},
}

function HarvestNodeDatabase.RollDrop(nodeId, rng)
	local node = HarvestNodeDatabase.Nodes[nodeId] or HarvestNodeDatabase.Corpses[nodeId]
	if not node then
		return nil
	end
	rng = rng or Random.new()
	local total = 0
	for _, d in ipairs(node.Drops) do
		total += d.Weight
	end
	local pick = rng:NextNumber() * total
	for _, d in ipairs(node.Drops) do
		pick -= d.Weight
		if pick <= 0 then
			return d.Item
		end
	end
	return node.Drops[#node.Drops].Item
end

return HarvestNodeDatabase
