-- GENERATED by ark-blox/tools/gen.py from tools/data.py. Do not edit by hand.
-- ASE vanilla item quality tiers (no Transcendent).

local QualityTiers = {}

QualityTiers.Order = { "PRIMITIVE", "RAMSHACKLE", "APPRENTICE", "JOURNEYMAN", "MASTERCRAFT", "ASCENDANT" }

QualityTiers.Tiers = {
	PRIMITIVE = {
		Id = "PRIMITIVE",
		Name = "Primitive",
		Index = 1,
		Multiplier = 1.0,
		Color = "#E6E6E6",
	},
	RAMSHACKLE = {
		Id = "RAMSHACKLE",
		Name = "Ramshackle",
		Index = 2,
		Multiplier = 1.25,
		Color = "#4CAF50",
	},
	APPRENTICE = {
		Id = "APPRENTICE",
		Name = "Apprentice",
		Index = 3,
		Multiplier = 2.5,
		Color = "#2196F3",
	},
	JOURNEYMAN = {
		Id = "JOURNEYMAN",
		Name = "Journeyman",
		Index = 4,
		Multiplier = 4.5,
		Color = "#9C27B0",
	},
	MASTERCRAFT = {
		Id = "MASTERCRAFT",
		Name = "Mastercraft",
		Index = 5,
		Multiplier = 7.0,
		Color = "#FFC107",
	},
	ASCENDANT = {
		Id = "ASCENDANT",
		Name = "Ascendant",
		Index = 6,
		Multiplier = 10.0,
		Color = "#00E5FF",
	},
}

-- Categories whose items roll quality. Structures never do.
QualityTiers.Categories = {
	Armor = true,
	Saddle = true,
	Shield = true,
	Tool = true,
	Weapon = true,
}

-- Building progression is separate from item quality. Greenhouse is a special set.
QualityTiers.BuildingTiers = { "Thatch", "Wood", "Stone", "Greenhouse", "Metal", "Tek" }

function QualityTiers.Get(id)
	return QualityTiers.Tiers[id] or QualityTiers.Tiers.PRIMITIVE
end

-- Returns the highest tier whose multiplier threshold is <= rolled multiplier.
function QualityTiers.FromMultiplier(mult)
	local best = QualityTiers.Tiers.PRIMITIVE
	for _, id in ipairs(QualityTiers.Order) do
		local t = QualityTiers.Tiers[id]
		if mult >= t.Multiplier then
			best = t
		end
	end
	return best
end

-- Scale a base stat (damage, durability, armor) by quality.
function QualityTiers.ScaleStat(base, id)
	return base * QualityTiers.Get(id).Multiplier
end

return QualityTiers
